#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haber.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="yeni")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertARABLAR(ARABLAR instance);
    partial void UpdateARABLAR(ARABLAR instance);
    partial void DeleteARABLAR(ARABLAR instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["yeniConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ARABLAR> ARABLARs
		{
			get
			{
				return this.GetTable<ARABLAR>();
			}
		}
		
		public System.Data.Linq.Table<OGRENCİLER> OGRENCİLERs
		{
			get
			{
				return this.GetTable<OGRENCİLER>();
			}
		}
		
		public System.Data.Linq.Table<URUNLER> URUNLERs
		{
			get
			{
				return this.GetTable<URUNLER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ARABLAR")]
	public partial class ARABLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _aracno;
		
		private string _marka;
		
		private string _model;
		
		private System.Nullable<int> _trafikyil;
		
		private string _renk;
		
		private string _yakit;
		
		private System.Nullable<int> _kilo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnaracnoChanging(string value);
    partial void OnaracnoChanged();
    partial void OnmarkaChanging(string value);
    partial void OnmarkaChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OntrafikyilChanging(System.Nullable<int> value);
    partial void OntrafikyilChanged();
    partial void OnrenkChanging(string value);
    partial void OnrenkChanged();
    partial void OnyakitChanging(string value);
    partial void OnyakitChanged();
    partial void OnkiloChanging(System.Nullable<int> value);
    partial void OnkiloChanged();
    #endregion
		
		public ARABLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aracno", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string aracno
		{
			get
			{
				return this._aracno;
			}
			set
			{
				if ((this._aracno != value))
				{
					this.OnaracnoChanging(value);
					this.SendPropertyChanging();
					this._aracno = value;
					this.SendPropertyChanged("aracno");
					this.OnaracnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marka", DbType="VarChar(10)")]
		public string marka
		{
			get
			{
				return this._marka;
			}
			set
			{
				if ((this._marka != value))
				{
					this.OnmarkaChanging(value);
					this.SendPropertyChanging();
					this._marka = value;
					this.SendPropertyChanged("marka");
					this.OnmarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(10)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trafikyil", DbType="Int")]
		public System.Nullable<int> trafikyil
		{
			get
			{
				return this._trafikyil;
			}
			set
			{
				if ((this._trafikyil != value))
				{
					this.OntrafikyilChanging(value);
					this.SendPropertyChanging();
					this._trafikyil = value;
					this.SendPropertyChanged("trafikyil");
					this.OntrafikyilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_renk", DbType="VarChar(10)")]
		public string renk
		{
			get
			{
				return this._renk;
			}
			set
			{
				if ((this._renk != value))
				{
					this.OnrenkChanging(value);
					this.SendPropertyChanging();
					this._renk = value;
					this.SendPropertyChanged("renk");
					this.OnrenkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yakit", DbType="VarChar(10)")]
		public string yakit
		{
			get
			{
				return this._yakit;
			}
			set
			{
				if ((this._yakit != value))
				{
					this.OnyakitChanging(value);
					this.SendPropertyChanging();
					this._yakit = value;
					this.SendPropertyChanged("yakit");
					this.OnyakitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kilo", DbType="Int")]
		public System.Nullable<int> kilo
		{
			get
			{
				return this._kilo;
			}
			set
			{
				if ((this._kilo != value))
				{
					this.OnkiloChanging(value);
					this.SendPropertyChanging();
					this._kilo = value;
					this.SendPropertyChanged("kilo");
					this.OnkiloChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OGRENCİLER")]
	public partial class OGRENCİLER
	{
		
		private short _ogrno;
		
		private string _ograd;
		
		private string _ogrsoyad;
		
		private string _velisoyad;
		
		private string _adres;
		
		private string _sinif;
		
		private System.Nullable<System.DateTime> _dogumtar;
		
		private string _alan;
		
		private string _kangrup;
		
		private string _dogumyer;
		
		public OGRENCİLER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrno", AutoSync=AutoSync.Always, DbType="SmallInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public short ogrno
		{
			get
			{
				return this._ogrno;
			}
			set
			{
				if ((this._ogrno != value))
				{
					this._ogrno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ograd", DbType="VarChar(15)")]
		public string ograd
		{
			get
			{
				return this._ograd;
			}
			set
			{
				if ((this._ograd != value))
				{
					this._ograd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrsoyad", DbType="VarChar(15)")]
		public string ogrsoyad
		{
			get
			{
				return this._ogrsoyad;
			}
			set
			{
				if ((this._ogrsoyad != value))
				{
					this._ogrsoyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_velisoyad", DbType="VarChar(20)")]
		public string velisoyad
		{
			get
			{
				return this._velisoyad;
			}
			set
			{
				if ((this._velisoyad != value))
				{
					this._velisoyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="VarChar(50)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this._adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinif", DbType="VarChar(4)")]
		public string sinif
		{
			get
			{
				return this._sinif;
			}
			set
			{
				if ((this._sinif != value))
				{
					this._sinif = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dogumtar", DbType="Date")]
		public System.Nullable<System.DateTime> dogumtar
		{
			get
			{
				return this._dogumtar;
			}
			set
			{
				if ((this._dogumtar != value))
				{
					this._dogumtar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alan", DbType="VarChar(3)")]
		public string alan
		{
			get
			{
				return this._alan;
			}
			set
			{
				if ((this._alan != value))
				{
					this._alan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kangrup", DbType="VarChar(3)")]
		public string kangrup
		{
			get
			{
				return this._kangrup;
			}
			set
			{
				if ((this._kangrup != value))
				{
					this._kangrup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dogumyer", DbType="VarChar(15)")]
		public string dogumyer
		{
			get
			{
				return this._dogumyer;
			}
			set
			{
				if ((this._dogumyer != value))
				{
					this._dogumyer = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URUNLER")]
	public partial class URUNLER
	{
		
		private int _urunno;
		
		private string _urunad;
		
		private string _uruntanim;
		
		private System.Nullable<decimal> _maliyet;
		
		private System.Nullable<double> _karoran;
		
		private System.Nullable<double> _kdv;
		
		public URUNLER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunno", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int urunno
		{
			get
			{
				return this._urunno;
			}
			set
			{
				if ((this._urunno != value))
				{
					this._urunno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunad", DbType="VarChar(15)")]
		public string urunad
		{
			get
			{
				return this._urunad;
			}
			set
			{
				if ((this._urunad != value))
				{
					this._urunad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uruntanim", DbType="VarChar(50)")]
		public string uruntanim
		{
			get
			{
				return this._uruntanim;
			}
			set
			{
				if ((this._uruntanim != value))
				{
					this._uruntanim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maliyet", DbType="Money")]
		public System.Nullable<decimal> maliyet
		{
			get
			{
				return this._maliyet;
			}
			set
			{
				if ((this._maliyet != value))
				{
					this._maliyet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_karoran", DbType="Float")]
		public System.Nullable<double> karoran
		{
			get
			{
				return this._karoran;
			}
			set
			{
				if ((this._karoran != value))
				{
					this._karoran = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kdv", DbType="Float")]
		public System.Nullable<double> kdv
		{
			get
			{
				return this._kdv;
			}
			set
			{
				if ((this._kdv != value))
				{
					this._kdv = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
